# docker-compose.yml
version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: /home/alaa/Desktop/DevOps16/backend
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
    networks:
      - app-network
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    ports:
      - "8082:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  frontend:
    build:
      context: /home/alaa/Desktop/DevOps16/beit
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:5000
    networks:
      - app-network
    ports:
      - "3001:3000"

  grafana:
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    image: grafana/grafana
    networks:
      - app-network
    ports:
      - "4000:3000"

  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home:rw

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - app-network
    ports:
      - "9091:9090"
    volumes:
      - /home/alaa/Desktop/DevOps16/prometheus.yml:/etc/prometheus/prometheus.yml:rw

volumes:
  jenkins_home: {}


# config map host and
# secretes grafana password
# 4 svc for each deployment NodePort
# 4 deployemnts for eachg application

# |
# v

# jenkins application